### ISSUE TITLE
[STAGE 3.2] [TASK 7] [US 3] Delete sponsors profile

### ISSUE THREAD

**Issue by CherkasovAndrii** [Team-Alexander/backend#107]
### Description
- [ ] Config email sender
- [ ] Create logic for schedule to delete a sponsors profile after a week(7 days)
#### URL
- /api/v1/sponsors/{sponsor-id}

#### Method 
- DELETE

#### Input parameters
- JWT Token

#### Output
- 204 No content

### What should we do in tests
- [ ] Add test in SponsorServiceTest:

- [ ] Add test in SponsorControllerTest

**Comment by Miroslav-Shashkin** [comment]
@VadymPratsybuda 

- [ ] Bug-68 : https://uptalent.atlassian.net/browse/U0-127
