### ISSUE TITLE
[STAGE 3.2] [TASK 8] [US 3] Restore sponsors profile after being deleted

### ISSUE THREAD

**Issue by CherkasovAndrii** [Team-Alexander/backend#108]
### Description
- [ ] Change login logic
#### URL
- /api/v1/sponsors/login

#### Method 
- POST

#### Input parameters
- SponsorsLogin

#### Output
- JWT Token

### What should we do in tests
- [ ] Add test in SponsorServiceTest:

- [ ] Add test in SponsorControllerTest

**Comment by Miroslav-Shashkin** [comment]
@VadymPratsybuda 

- [ ] Bug-65 : https://uptalent.atlassian.net/browse/U0-124
- [ ] Bug-66 : https://uptalent.atlassian.net/browse/U0-125
- [ ] Bug-67 : https://uptalent.atlassian.net/browse/U0-126
