### ISSUE TITLE
[STAGE 2] [TASK 3] [US 3] Create new proof [Endpoint]

### ISSUE THREAD

**Issue by MarkHmnv** [Team-Alexander/backend#64]
### Prerequisites before implementing
- #62

#### URL
- /api/v1/talent/{talent-id}/proofs

#### Method 
- POST

#### Input parameters
- JWT token
- ProofEdit

#### Output
- ID of Proof

### What should we do in realization
- [x] Create ProofModify
- [x] Create method createProof in ProofService
- [x] Create method createProof in ProofController
### What should we do in tests
- [x] Add new test to ProofServiceTest
  - [x] createProofSuccessfully
  - [x] createProofOtherTalent
- [x] Add new test to ProofControllerTest
  - [x] createProofSuccessfully
  - [x] createProofOtherTalent

**Comment by Miroslav-Shashkin** [comment]
@MarkHmnv 
 - [ ] Bug-92(proof/vacancy) : https://uptalent.atlassian.net/browse/U0-167
