### ISSUE TITLE
[STAGE 2] [TASK 7] [US 7] Delete proof [Endpoint]

### ISSUE THREAD

**Issue by MarkHmnv** [Team-Alexander/backend#67]
### Prerequisites before implementing
- #62

#### URL
- /api/v1/talent/{talent-id}/proofs/{proof-id}

#### Method 
- DELETE

#### Input parameters
- JWT token
- Proof id
#### Output
- No content

### What should we do in realization
- [x] Create method deleteProof in ProofService
- [x] Create method deleteProof in ProofController
### What should we do in tests
- [x] Add new test to ProofServiceTest
  - [x] deleteProofSuccessfully
  - [x] deleteNotExistProof
  - [x] deleteProofFromOtherTalent 
- [x] Add new test to ProofControllerTest
  - [x] deleteProofSuccessfully
  - [x] deleteNotExistProof
  - [x] deleteProofFromOtherTalent

**Comment by Miroslav-Shashkin** [comment]
@CherkasovAndrii 

- [ ] Bug-78 : https://uptalent.atlassian.net/browse/U0-143
